events {
    worker_connections 1024;
}

http {
    upstream notes_service {
        server notes-service:5001;
    }

    upstream external_service {
        server external-service:5002;
    }

    server {
        listen 80;

        location /notes {
            proxy_pass http://notes_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /external {
            proxy_pass http://external_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
